MonsterNames:
	db "RHYDON@@@@"
	db "KANGASKHAN"
	db "nidonlas@@" ;db "NIDORAN♂@@"
	db "lurcridas@" ;db "CLEFAIRY@@"
	db "tunpasr@@@" ;db "SPEAROW@@@"
	db "VOLTORB@@@"
	db "nidonaus@@" ;db "NIDOKING@@"
	db "snobun@@@@" ;db "SLOWBRO@@@"
	db "iedryrespa" ;db "IVYSAUR@@@" ivy-reptile
	db "EXEGGUTOR@"
	db "LICKITUNG@"
	db "EXEGGCUTE@"
	db "GRIMER@@@@"
	db "gengar@@@@" ;db "GENGAR@@@@"
        db "nidoxlis@@" ;db "NIDORAN♀@@"
	db "nidonim@@@" ;db "NIDOQUEEN@"
	db "CUBONE@@@@"
	db "RHYHORN@@@"
	db "LAPRAS@@@@"
	db "balgerkus@" ;db "ARCANINE@@"
	db "mius@@@@@@" ;db "MEW@@@@@@@"
	db "GYARADOS@@"
	db "SHELLDER@@"
	db "nulsnider@" ;db "TENTACOOL@"
	db "pruxis@@@@" ;db "GASTLY@@@@"
	db "SCYTHER@@@"
	db "STARYU@@@@"
	db "cesycakys@" ;db "BLASTOISE@"
	db "PINSIR@@@@"
	db "TANGELA@@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "dagerkus@@" ;db "GROWLITHE@"
	db "sincroniks" ;db "ONIX@@@@@@"
	db "tepasr@@@@" ;db "FEAROW@@@@"
        db "cmakolom@@" ;db "PIDGEY@@@@"
	db "snobeb@@@@" ;db "SLOWPOKE@@"
	db "kadabras@@" ;db "KADABRA@@@"
	db "fegro'is@@" ;db "GRAVELER@@"
	db "selfu'as@@" ;db "CHANSEY@@@"
	db "rebirda'as" ;db "MACHOKE@@@"
	db "MR.MIME@@@"
	db "HITMONLEE@"
	db "HITMONCHAN"
	db "edipales@@" ;db "ARBOK@@@@@"
	db "ledbirdus@" ;db "PARASECT@@"
	db "mojdatkas@" ;db "PSYDUCK@@@"
	db "DROWZEE@@@"
	db "golym@@@@@" ;db "GOLEM@@@@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "MAGMAR@@@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "ELECTABUZZ"
	db "cibvolmak@" ;db "MAGNETON@@"
	db "KOFFING@@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "dabsmanis@" ;db "MANKEY@@@@"
	db "SEEL@@@@@@"
	db "cautup@@@@" ;db "DIGLETT@@@"
	db "TAUROS@@@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
        db "sugydatka@" ;db "FARFETCH'D"
	db "vidipterid" ;db "VENONAT@@@"
	db "DRAGONITE@"
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "cipnrdore@" ;db "DODUO@@@@@"
	db "cmasarlus@" ;db "POLIWAG@@@"
	db "JYNX@@@@@@"
	db "MOLTRES@@@"
	db "ARTICUNO@@"
	db "ZAPDOS@@@@"
	db "go'is@@@@@" ;db "DITTO@@@@@"
	db "nias@@@@@@" ;db "MEOWTH@@@@"
	db "KRABBY@@@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "lorxunres@" ;db "VULPIX@@@@"
	db "fengumixos" ;db "NINETALES@"
	db ".ipkatcu@@" ;db "PIKACHU@@@"
	db "raitcus@@@" ;db "RAICHU@@@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "DRATINI@@@"
	db "DRAGONAIR@"
	db "KABUTO@@@@"
	db "KABUTOPS@@"
	db "HORSEA@@@@"
	db "SEADRA@@@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "sansmacus@" ;db "SANDSHREW@"
	db "sanratcus@" ;db "SANDSLASH@"
	db "OMANYTE@@@"
	db "OMASTAR@@@"
	db "cmasipnas@" ;db "JIGGLYPUFF"
	db "brasipnas@" ;db "WIGGLYTUFF"
	db "ivis@@@@@@" ;db "EEVEE@@@@@"
	db "fagyxi'an@" ;db "FLAREON@@@"
	db "jenxi'an@@" ;db "JOLTEON@@@"
	db "jauxi'an@@" ;db "VAPOREON@@"
	db "verda'as@@" ;db "MACHOP@@@@"
	db "fazycirop@" ;db "ZUBAT@@@@@"
	db "ecnis@@@@@" ;db "EKANS@@@@@"
	db "ledcinkis@" ;db "PARAS@@@@@"
	db "nulsarlus@" ;db "POLIWHIRL@"
	db "brasarlus@" ;db "POLIWRATH@"
        db "curvidnus@" ;db "WEEDLE@@@@"
        db "vidjemnas@" ;db "KAKUNA@@@@"
        db "vidapis@@@" ;db "BEEDRILL@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "cipnrdoci@" ;db "DODRIO@@@@"
	db "sonsmanis@" ;db "PRIMEAPE@@"
	db "cibcautup@" ;db "DUGTRIO@@@"
	db "vidxeteros" ;db "VENOMOTH@@"
	db "DEWGONG@@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "curkiatas@" ;db "CATERPIE@@"
        db "curjemnas@" ;db "METAPOD@@@"
        db "ziflepid@@" ;db "BUTTERFREE"
	db "vobirda'as" ;db "MACHAMP@@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "jaudatkas@" ;db "GOLDUCK@@@"
	db "HYPNO@@@@@"
	db "blucirop@@" ;db "GOLBAT@@@@"
	db "miures@@@@" ;db "MEWTWO@@@@"
	db "SNORLAX@@@"
	db "MAGIKARP@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "MUK@@@@@@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "KINGLER@@@"
	db "CLOYSTER@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "ELECTRODE@"
        db "luranmis@@" ;db "CLEFABLE@@"
	db "WEEZING@@@"
	db "prcinfos@@" ;db "PERSIAN@@@"
	db "MAROWAK@@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "tepru'is@@" ;db "HAUNTER@@@"
	db "abras@@@@@" ;db "ABRA@@@@@@"
	db "alykazam@@" ;db "ALAKAZAM@@"
        db "nulkolom@@" ;db "PIDGEOTTO@"
        db "brakolom@@" ;db "PIDGEOT@@@"
	db "STARMIE@@@"
	db "baljyrespa" ;db "BULBASAUR@"
        db "kavbyrespa" ;db "VENUSAUR@@"
	db "kusnider@@" ;db "TENTACRUEL"
	db "crina'us@@" ;db "MISSINGNO."
	db "GOLDEEN@@@"
	db "SEAKING@@@"
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "fagekus@@@" ;db "PONYTA@@@@"
	db "fagkabalus" ;db "RAPIDASH@@"
	db "cmaratus@@" ;db "RATTATA@@@"
	db "braratus@@" ;db "RATICATE@@"
	db "nidonlarel" ;db "NIDORINO@@"
	db "nidoxlirel" ;db "NIDORINA@@"
	db "fegbidjus@" ;db "GEODUDE@@@"
	db "kubycpis@@" ;db "PORYGON@@@"
	db "AERODACTYL"
	db "crina'us@@" ;db "MISSINGNO."
	db "volmak@@@@" ;db "MAGNEMITE@"
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "jelkaudat@" ;db "CHARMANDER"
	db "digycakys@" ;db "SQUIRTLE@@"
	db "jelkamelon" ;db "CHARMELEON"
	db "soncakys@@" ;db "WARTORTLE@"
	db "jeldrakos@" ;db "CHARIZARD@"
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "crina'us@@" ;db "MISSINGNO."
	db "pezciblus@" ;db "ODDISH@@@@"
	db "sumnerul@@" ;db "GLOOM@@@@@"
	db "vindurul@@" ;db "VILEPLUME@"
	db "vernepens@" ;db "BELLSPROUT"
	db "vidnepens@" ;db "WEEPINBELL"
	db "rainepens@" ;db "VICTREEBEL"
